config/routes.rb
WebStore::Application.routes.draw do

  resources :users
  resources :sessions, :only => [:new, :create, :destroy]

  resources :products do
    put 'add_to_cart'
  end

  delete "/logout", :to => "sessions#destroy"

  resources :carts
end

app/models/order.rb
class Order < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :name, :price
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :password

  validates :email, :password, :presence => true
  validates :email, :uniqueness => true

  before_save :create_remember_token

  def checkout
    @product_ids = cookies[:cart].split
    @user = User.find(params[:id])
  end

  private

  def create_remember_token
    self.remember_token = SecureRandom.urlsafe_base64
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper

  def handle_unverified_request
    sign_out
    super
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_filter :require_login

  def show
    @product_ids = cookies[:cart].split
  end

  def update
  end

  def checkout
    @product_ids = cookies[:cart].split
    @current_user
  end

  def destroy
    cookies[:cart] = ''
  end

  private

  def require_login
    unless signed_in?
      flash[:error] = "You must log in before interacting with your cart."
      redirect_to new_sessions_url
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(params[:product])

    if @product.save
      flash[:success] = "Product created!"
      redirect_to product_url(@product)
    else
      render :new
    end
  end

  def show
    @product = Product.find(params[:id])
  end

  def add_to_cart
    @product = Product.find(params[:product_id])
    cookies[:cart] += " #{@product.id}"

    flash[:success] = "#{@product.name} added to cart."

    redirect_to product_url(@product)
  end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by_email(params[:session][:email])
    if user
      sign_in(user)
      flash[:success] = "logged in"
      redirect_to user_url(user)
    else
      flash[:failure] = "log in failed"
      render :new
    end
  end

  def destroy
    sign_out
    empty_cart
    redirect_to users_url
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])

    if @user.save
      sign_in(@user)
      flash[:success] = "User created!"
      redirect_to user_url(@user)
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper

  def cart
    cookies[:cart] ||= []
  end

end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    cookies.permanent[:remember_token] = user.remember_token
    cookies[:cart] = ''
    self.current_user = user
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    @current_user ||= User.find_by_remember_token(cookies[:remember_token])
  end

  def signed_in?
    !current_user.nil?
  end

  def sign_out
    self.current_user = nil
    cookies.delete(:remember_token)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/carts/show.html.erb
<h1>Cart</h1>
<p>
  <ul>
    <% @product_ids.each do |product_id| %>
    <li><%= Product.find(product_id.to_i).inspect %></li>
    <% end %>
  </ul>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WebStore</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <% flash.each do |key, value| %>
          <div class="alert alert-<%= key %>"><%= value %></div>
    <% end %>
    <%= yield %>
  </div>
</body>
</html>

app/views/products/index.html.erb
<h1>Products</h1>
<p>
  <ul>
    <% @products.each do |product| %>
      <li><%= product.inspect %></li>
    <% end %>
  </ul>
</p>

app/views/products/new.html.erb
<h1>Create Product</h1>

<%= form_for(@product) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <br>
  <%= f.label :price %>
  <%= f.text_field :price %>
  <br>
  <%= f.submit %>
<% end %>

app/views/products/show.html.erb
<h1>Product Detail</h1>
<p>
  <%= @product.inspect %>
</p>
<%= link_to("Add item to cart", product_add_to_cart_url(@product), :method => :put) %>

app/views/users/checkout.html.erb
<h1>Checkout</h1>
<%= form_for(@product_ids) do |f| %>
<% end %>

app/views/users/index.html.erb
<h1>User Index</h1>

app/views/users/new.html.erb
<%= form_for(@user) do |f| %>
  <%= f.label :email %>
  <%= f.text_field :email %>
  <br>
  <%= f.label :password %>
  <%= f.text_field :password %>
  <br>
  <%= f.submit %>

<% end %>

app/views/users/show.html.erb
<h1>User Details</h1>

<%= @user.inspect %>